exports.__doc__ = "NAME\n".yellow
    + "\t_colors\n"
    + "\n"
    + "MODULE DOCS\n".yellow
    + "\thttps://github.com/Marak/colors.js\n"
    + "\n"
    + "DESCRIPTION\n".yellow
    + "\tget color and style in your node.js console http://bit.ly/yIWvPi\n"
    + "\n"
    + "\tcolors and styles:\n"
    + "\t - bold\n"
    + "\t - italic\n"
    + "\t - underline\n"
    + "\t - inverse\n"
    + "\t - yellow\n"
    + "\t - cyan\n"
    + "\t - white\n"
    + "\t - magenta\n"
    + "\t - green\n"
    + "\t - red\n"
    + "\t - grey\n"
    + "\t - blue\n"
    + "\t - rainbow\n"
    + "\t - zebra\n"
    + "\t - random\n\n"
    + "\n"
    + "\tUsage:\n"
    + "\t console.log('hello'.green); // outputs green text\n"
    + "\t console.log('i like cake and pies'.underline.red) // outputs red underlined text\n"
    + "\t console.log('inverse the color'.inverse); // inverses the color\n"
    + "\t console.log('OMG Rainbows!'.rainbow); // rainbow (ignores spaces)\n"
    ;
